name: travelverse_mobile_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  adobe_xd: ^2.0.1
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.11
  flutter_svg: ^1.1.6
  google_fonts: 6.1.0
  http: ^1.2.0
  json_serializable: ^6.8.0
  shared_preferences: ^2.2.3
  json_annotation: ^4.9.0
  provider: ^6.1.2
  flutter_downloader: ^1.11.7
  permission_handler: ^11.3.1
  dio: ^5.7.0
  open_file: ^3.3.2
  path_provider: ^2.1.4
  fluttertoast: ^8.2.5

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  fonts:
      - family: Poppins
        fonts:
          - asset: fonts/Poppins-Regular.ttf
          - asset: fonts/Poppins-Light.ttf
            weight: 300
          - asset: fonts/Poppins-SemiBold.ttf
            weight: 600
          - asset: fonts/Poppins-Bold.ttf
            weight: 700
          - asset: fonts/Poppins-Medium.ttf
            weight: 500
  uses-material-design: true

  

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/images/ManWithLuggage.png